MvcCoreUtilidades/Models/ErrorViewModel.cs
namespace MvcCoreUtilidades.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreUtilidades/Controllers/CachingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace MvcNetCoreUtilidades.Controllers
{
    public class CachingController : Controller
    {
        private IMemoryCache memoryCache;

        public CachingController(IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MemoriaPersonalizada(int? tiempo)
        {
            if (tiempo == null)
            {
                tiempo = 60;
            }
            string fecha = DateTime.Now.ToLongDateString() + "--" + DateTime.Now.ToLongTimeString();
            if (this.memoryCache.Get("FECHA") == null)
            {
                MemoryCacheEntryOptions options = new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromSeconds(tiempo.Value));
                this.memoryCache.Set("FECHA", fecha, options);
                ViewData["MENSAJE"] = "Fecha almacenada correctamente";
                ViewData["FECHA"] = this.memoryCache.Get("FECHA");
            }
            else
            {
                fecha = this.memoryCache.Get<string>("FECHA");
                ViewData["MENSAJE"] = "Fecha recuperada correctamente";
                ViewData["FECHA"] = fecha;
            }
            return View();
        }

        [ResponseCache(Duration = 15, Location = ResponseCacheLocation.Client)]
        public IActionResult MemoriaDistribuida()
        {
            string fecha = DateTime.Now.ToLongDateString() + "--" + DateTime.Now.ToLongTimeString();
            ViewData["FECHA"] = fecha;
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/CifradosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;

namespace MvcCoreUtilidades.Controllers
{
    public class CifradosController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CifradoBasico()
        {
            return View();
        }

        public IActionResult CifradoEficiente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoEficiente(string contenido, string resultado, string accion)
        {
            if (accion.ToLower() == "cifrar")
            {
                string response = HelperCryptography.CifrarContenido(contenido, false);
                ViewData["TEXTOCIFRADO"] = response;
                ViewData["SALT"] = HelperCryptography.Salt;
            }
            else if (accion.ToLower() == "comparar")
            {
                string response = HelperCryptography.CifrarContenido(contenido, true);
                if (response != resultado)
                {
                    ViewData["MENSAJE"] = "Los datos son distintos...";
                }
                else
                {
                    ViewData["MENSAJE"] = "Los datos son IGUALES!!!";
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult CifradoBasico(string contenido, string resultado, string accion)
        {
            string response =
            HelperCryptography.EncriptarTextoBasico(contenido);
            if (accion.ToLower() == "cifrar")
            {
                ViewData["TEXTOCIFRADO"] = response;
            }
            else if (accion.ToLower() == "comparar")
            {
                if (response != resultado)
                {
                    ViewData["MENSAJE"] = "Los datos no coinciden";
                }
                else
                {
                    ViewData["MENSAJE"] = "Contenidos iguales!!!";
                }
            }
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Models;

namespace MvcCoreUtilidades.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreUtilidades/Controllers/MailsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace MvcCoreUtilidades.Controllers
{
    public class MailsController : Controller
    {
        private IConfiguration configuration;

        public MailsController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public IActionResult SendMail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMail(string to, string asunto, string mensaje)
        {
            string user = this.configuration.GetValue<string>("MailSettings:Credentials:User");
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress(user);
            mail.To.Add(to);
            mail.Subject = asunto;
            mail.Body = mensaje;
            mail.IsBodyHtml = true;
            mail.Priority = MailPriority.Normal;
            string password = this.configuration.GetValue<string>("MailSettings:Credentials:Password");
            string host = this.configuration.GetValue<string>("Server:Host");
            int port = this.configuration.GetValue<int>("Server:Port");
            bool ssl = this.configuration.GetValue<bool>("Server:Ssl");
            bool defaultCredentials = this.configuration.GetValue<bool>("Server:DefaultCredentials");
            SmtpClient client = new SmtpClient();
            client.Host = host;
            client.Port = port;
            client.EnableSsl = ssl;
            client.UseDefaultCredentials = defaultCredentials;  // Set BEFORE credentials
            NetworkCredential credentials = new NetworkCredential(user, password);
            client.Credentials = credentials;  // Set AFTER
            await client.SendMailAsync(mail);
            ViewData["MENSAJE"] = "Mensaje enviado correctamente.";
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/UploadFilesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreUtilidades.Helpers;

namespace MvcCoreUtilidades.Controllers
{
    public class UploadFilesController : Controller
    {
        private HelperPathProvider helper;

        public UploadFilesController(HelperPathProvider helper)
        {
            this.helper = helper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SubirFile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubirFile(IFormFile fichero)
        {
            string fileName = fichero.FileName;
            string path =
            this.helper.MapPath(fileName, Folders.Images);
            string urlPath =
            this.helper.MapUrlPath(fileName, Folders.Images);
            //PARA SUBIR FICHEROS UTILIZAMOS Str    eam 
            using (Stream stream = new FileStream(path, FileMode.Create))
            {
                await fichero.CopyToAsync(stream);
            }
            ViewData["MENSAJE"] = "Fichero subido a "
            + path;
            ViewData["URLPATH"] = urlPath;
            return View();
        }
    }
}

MvcCoreUtilidades/Views/Caching/Index.cshtml
<h1>Ejemplos Caching</h1>
<ul class="list-group">
	<li>
		<a asp-controller="Caching" asp-action="MemoriaDistribuida">Memoria distribuida</a>
	</li>
	<li>
		<a asp-controller="Caching" asp-action="MemoriaPersonalizada">Memoria personalizada</a>
	</li>
</ul>

MvcCoreUtilidades/Views/Caching/MemoriaDistribuida.cshtml
<h1>Memoria Distribuida</h1>

<p><a asp-controller="Caching" asp-action="MemoriaDistribuida">Actualizar página</a></p>
<h2 style="color: blue">@ViewData["FECHA"]</h2>

MvcCoreUtilidades/Views/Caching/MemoriaPersonalizada.cshtml
<h1>Memoria Personalizada</h1>

<p>
	<a asp-controller="Caching" asp-action="MemoriaPersonalizada">Actualizar página</a>
</p>
<p>
	<a asp-controller="Caching" asp-action="MemoriaPersonalizada" asp-route-tiempo="15">Actualizar página 15 sg</a>
</p>
<p>
	<a asp-controller="Caching" asp-action="MemoriaPersonalizada" asp-route-tiempo="30">Actualizar página 30sg</a>
</p>
<h2 style="color: blue">@ViewData["MENSAJE"]</h2>
<h2 style="color: red">@ViewData["FECHA"]</h2>

MvcCoreUtilidades/Views/Cifrados/CifradoBasico.cshtml
<h1>Cifrado básico Texto</h1>

<form method="post" class="my-2">
    <label>Contenido a cifrar: </label>
    <input type="text" name="contenido" class="form-control" />
    <label class="mt-1">Resultado cifrado: </label>
    <textarea rows="5" name="resultado" class="form-control">@ViewData["TEXTOCIFRADO"]</textarea>
    <button class="btn btn-info my-2" name="accion" value="cifrar">
    Cifrar contenido
    </button>
    <button class="btn btn-danger" name="accion" value="comparar">
    Comparar cifrado
    </button>
</form>
<h2 style="color: blue">@ViewData["MENSAJE"]</h2>

MvcCoreUtilidades/Views/Cifrados/CifradoEficiente.cshtml
<h1>Cifrado Eficiente</h1>

<form method="post" class="my-2">
    <label>Contenido a cifrar: </label>
    <input type="text" name="contenido" class="form-control" />
    <label class="mt-1">Resultado cifrado: </label>
    <textarea rows="5" name="resultado" class="form-control">@ViewData["TEXTOCIFRADO"]</textarea>
    <button class="btn btn-info my-2" name="accion" value="cifrar">
        Cifrar contenido
    </button>
    <button class="btn btn-danger" name="accion" value="comparar">
        Comparar cifrado
    </button>
</form>
<h3 style="color:red">@ViewData["SALT"]</h3>
<h2 style="color:blue">@ViewData["MENSAJE"]</h2>

MvcCoreUtilidades/Views/Cifrados/Index.cshtml
<h1>Menú cifrado</h1>

<ul class="list-group">
    <li class="list-group-item">
        <a asp-controller="Cifrados" asp-action="CifradoBasico">Cifrado Básico</a>
    </li>
    <li class="list-group-item">
        <a asp-controller="Cifrados" asp-action="CifradoEficiente">Cifrado Eficiente</a>
    </li>
</ul>

MvcCoreUtilidades/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreUtilidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreUtilidades</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caching" asp-action="Index">Caching</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mails" asp-action="SendMail">Mails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrados" asp-action="Index">Cifrados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCoreUtilidades/Views/UploadFiles/SubirFile.cshtml
<h1>
    Subir ficheros Net Core
</h1>

<form method="post" enctype="multipart/form-data" class="my-2">
    <label>Seleccione un fichero: </label>
    <input type="file" name="fichero" class="form-control"/>
    <button class="btn btn-info mt-2">Subir fichero</button>
</form>

<img src='~/uploads/@ViewData["FILENAME"]'/>

<h2 style="color:blue">
    @ViewData["MENSAJE"]
</h2>